### ISSUE TITLE
Handwriting datasets

### ISSUE THREAD

**Issue by wdp-007** [amazon-research/textadain-robust-recognition#1]
Thanks for your good job!
Can you release the handwriting datasets ?

**Comment by onuriel** [comment]
Thanks!
Unfortunately, I can't release the handwriting datasets, as per there user agreements, I am not able to distribute it. However they are public so:
IAM can be found in https://fki.tic.heia-fr.ch/databases/iam-handwriting-database.
RIMES can be found http://www.a2ialab.com/doku.php?id=rimes_database:start - but the link isn't working at the moment.
and CVL can be found https://cvl.tuwien.ac.at/research/cvl-databases/an-off-line-database-for-writer-retrieval-writer-identification-and-word-spotting/

Good luck!
