### ISSUE TITLE
Will the pre-trained weights on handwritten data be made public?

### ISSUE THREAD

**Issue by wdp-007** [amazon-research/textadain-robust-recognition#2]
Will the pre-trained weights on handwritten data be made public?

**Comment by onuriel** [comment]
Hi, 

Thank you for taking interest in our work and I apologize for the late reply.

At this time, we don't plan on releasing the weights.

If you have any questions as to how to reproduce the results you are more than welcome to ask and I will be happy to assist.

Thanks!
